// pages/resume.tsx
import Head from 'next/head'

import { resumeCol } from '../lib/data'
import type { Linear, Resume } from '../types/resume'
import Style from '../styles/resume.module.scss'

interface Sorting extends Linear {
  sortDate: Date | null
}

function slimUrl(url: string) {
  return (`${url}`).replace('https://', '')
}

function Home({
  location,
  name,
  email,
  url,
  github,
  objective,
  languages,
  education,
  experience,
}: Resume) {
  return (
    <div className={Style.resume}>
      <Head>
        <title>Jeff Fasulkey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Style.heading}>{name}</div>
      <div className={Style.contact}>
        <ul>
          <li>{location}</li>
          <br />
          <li>
            <a href={`mailto:${email}`}>{email}</a>
          </li>
          <li>
            <a href={url}>{slimUrl(url)}</a>
            <br />
            <a href={github}>{slimUrl(github)}</a>
          </li>
          <li>
            <a href="/docs/fasulkey-resume.pdf" target="_blank">
              download pdf
            </a>
          </li>
        </ul>
      </div>
      <div className={Style['sub-heading']}>Objective:</div>
      <div className={Style.content}>{objective}</div>
      <div className={Style['sub-heading']}>Languages, Software, Etc:</div>
      <div className={Style.languages}>
        <ul>
          {languages?.map((l: string, i: number) => (
            <li key={i}>{l}</li>
          ))}
        </ul>
      </div>
      <div className={Style['sub-heading']}>Experience:</div>
      {experience?.map((e: Linear, i: number) => (
        <div className={Style.content} key={i}>
          <span className={(Style['job-title'], Style.stronger)}>
            {e.title}
          </span>
          <br />
          {`${e.location
            } ${
            e.startDate
            }-${
            e.endDate ? e.endDate : 'Present'}`}
          <br />
          <span className="stronger">{e.subTitle}</span>
          <ul>
            {e?.points?.map((p, i) => (
              <li key={i}>{p}</li>
            ))}
          </ul>
        </div>
      ))}

      <div className={Style['sub-heading']}>Education:</div>
      <div className={Style.languages}>
        <ul>
          {education?.map((e: Linear, i: number) => (
            <li key={i} className={Style['top-padding']}>
              <span className={(Style['job-title'], Style.stronger)}>
                {e.title}
              </span>
              <br />
              {e.location}
              <br />
              <span className={Style.stronger}>{e.subTitle}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const base = await resumeCol.getResume({ type: 'non-linear' })
  const education = await resumeCol.getResume({ type: 'education' })
  const experience = (await resumeCol.getResume({ type: 'experience' }))
    .map((e) => {
      const [month, year] = (`${e.endDate}`).split('-')
      e.sortDate = e.endDate
        ? new Date(Number(year), Number(month) - 1)
        : new Date()
      return e as Sorting
    })
    .sort((a, b) => (b.sortDate as any) - (a.sortDate as any))
    .map((el) => {
      el.sortDate = null
      return el
    })
  return { props: { ...base[0], education, experience } }
}

export default Home

// ui/src/views/resume.vue
<template>
    <div>
        <div v-if="$apollo.loading" class="container">
            <semipolar-spinner
                class="center-loader"
                :animation-duration="2000"
                :size="65"
                color="white"
            />
        </div>

        <transition name="fade">
            <div v-if="!$apollo.loading">
                <div class="heading">
                    {{ resume.name }}
                </div>
                <div class="contact">
                    <ul>
                        <li>{{ resume.location }}</li
                        ><br />
                        <li>
                            <a :href="'mailto:' + resume.email">{{
                                resume.email
                            }}</a>
                        </li>
                        <li>
                            <a :href="resume.url">{{
                                slimUrl({ url: resume.url })
                            }}</a
                            ><br />

                            <a :href="resume.github">{{
                                slimUrl({ url: resume.github })
                            }}</a>
                        </li>
                        <li>
                            <a
                                href="/assets/docs/fasulkey-resume.pdf"
                                target="_blank"
                                >download pdf</a
                            >
                        </li>
                    </ul>
                </div>
                <div class="sub-heading">Objective:</div>
                <div class="content">{{ resume.objective }}</div>
                <div class="sub-heading">Languages, Software, Etc:</div>
                <div class="languages">
                    <ul>
                        <li v-for="(l, i) in resume.languages" :key="i">
                            {{ l }}
                        </li>
                    </ul>
                </div>
                <div class="sub-heading">Experience:</div>
                <div
                    v-for="(e, i) in resume.experience"
                    :key="i"
                    class="content"
                >
                    <span class="job-title stronger">{{ e.title }}</span
                    ><br />
                    {{ e.location }} {{ e.startDate }} -
                    {{ e.endDate ? `${e.endDate}` : 'Present' }} <br />
                    <span class="stronger">{{ e.subTitle }}</span>
                    <ul>
                        <li v-for="(p, pi) in e.points" :key="pi">
                            {{ p }}
                        </li>
                    </ul>
                </div>

                <div class="sub-heading">Education:</div>
                <div class="languages">
                    <ul>
                        <li
                            v-for="(e, i) in resume.education"
                            :key="i"
                            class="top-padding"
                        >
                            <span class="job-title stronger">{{ e.title }}</span
                            ><br />
                            {{ e.location }}<br />
                            <span class="stronger">{{ e.subTitle }}</span>
                        </li>
                    </ul>
                </div>

                <div v-if="resume.affiliations && resume.affiliations.length">
                    <div class="sub-heading">Affiliations:</div>
                    <div class="languages">
                        <ul>
                            <li
                                v-for="(a, i) in resume.affiliations"
                                :key="i"
                                class="top-padding"
                            >
                                <span class="job-title stronger">{{
                                    a.title
                                }}</span
                                ><br />
                                <span class="stronger">{{ a.subTitle }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="footer"></div>
            </div>
        </transition>
    </div>
</template>

<script>
import gql from 'graphql-tag'
import SemipolarSpinner from 'epic-spinners/src/components/lib/SemipolarSpinner'
export default {
    name: `Resume`,

    components: {
        SemipolarSpinner
    },

    apollo: {
        resume: {
            query: gql`
                query Resume {
                    resume {
                        name
                        languages
                        github
                        location
                        objective
                        email
                        url
                        affiliations {
                            title
                            subTitle
                        }
                        experience {
                            title
                            subTitle
                            location
                            startDate
                            points
                            endDate
                        }
                        education {
                            title
                            subTitle
                            location
                        }
                    }
                }
            `
        }
    },
    data() {
        return {
            resume: {}
        }
    },
    methods: {
        slimUrl({ url }) {
            return (`` + url).replace(`https://`, ``)
        }
    }
}
</script>

<style lang="scss"></style>
